### ISSUE TITLE
Document how to properly cite distance3d

### ISSUE THREAD

**Issue by AlexanderFabisch** [AlexanderFabisch/distance3d#88]
CITATION.cff
```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Fabisch
    given-names: Alexander
    orcid: https://orcid.org/0000-0003-2824-7956
  - family-names: Behn
    given-names: Maarten
title: "distance3d: Distance computation and collision detection in 3D"
doi: 10.5281/zenodo.6509736
url: https://github.com/AlexanderFabisch/distance3d
type: software
```
